title: BRIN High Performance Computing Workshop
description: Workshop untuk penggunaan High Performance Computing (HPC) di BRIN
theme: just-the-docs

# Use custom color scheme
color_scheme: hpcw

# Callout setting
callouts:
  catatan:
    title: Catatan
    color: yellow
  warning:
    title: Warning
    color: red

# Use custom footer
footer_content: "Copyright &copy; 2023 Himawan Winarto. Disediakan di bawah lisensi <a href=\"https://creativecommons.org/licenses/by-nc/4.0/deed.id\">CC BY-NC 4.0</a>."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%F" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Enable or disable the site search
# Supports true (default) or false
search_enabled: false

# Fix HTML Compression
compress_html:
  blanklines: true

# Collections
collections:
  persiapan:
    output: true
  workshop_1:
    output: true
  workshop_2:
    output: true
  workshop_3:
    output: true
  workshop_4:
    output: true
  workshop_5:
    output: true
  workshop_6:
    output: true
  workshop_7:
    output: true

# Configure just_the_docs for collections
just_the_docs:
  collections:
    persiapan:
      name: Persiapan
    workshop_1:
      name: Workshop I
    workshop_2:
      name: Workshop II
    workshop_3:
      name: Workshop III
    workshop_4:
      name: Workshop IV
    workshop_5:
      name: Workshop V
    workshop_6:
      name: Workshop VI
    workshop_7:
      name: Workshop VII
